{{- if not .Values.demoCredentials.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "agenteval.fullname" . }}
  labels:
    {{- include "agenteval.labels" . | nindent 4 }}
type: Opaque
stringData:
  postgres-user: {{ .Values.demoCredentials.postgresUser | quote }}
  postgres-password: {{ .Values.demoCredentials.postgresPassword | quote }}
  postgres-database: {{ .Values.demoCredentials.postgresDatabase | quote }}
{{- end }}
