import type { DemoWorkflowState } from "./model";

export function cloneDemoWorkflowFixtures(
  projectId: string,
  demoSessionId: string,
): DemoWorkflowState {
  const createdAt = "2026-08-01T09:00:00.000Z";
  return structuredClone({
    demoSessionId,
    projectId,
    agents: [
      {
        id: "fixture-policy-guidance",
        demoSessionId,
        projectId,
        source: "FIXTURE",
        createdByPersona: "admin",
        createdAt,
        updatedAt: createdAt,
        name: "Policy Guidance Assistant",
        owner: "Policy Operations",
        description: "Answers policy questions using approved guidance.",
        businessOutcome: "Consistent policy guidance for service teams",
        targetUsers: "Service representatives",
        typicalScenarios: ["Policy lookup", "Escalation guidance"],
        currentApprovedRevisionId: "fixture-policy-guidance-r1",
        activeDraftRevisionId: null,
      },
    ],
    agentRevisions: [
      {
        id: "fixture-policy-guidance-r1",
        demoSessionId,
        projectId,
        source: "FIXTURE",
        createdByPersona: "admin",
        createdAt,
        updatedAt: createdAt,
        agentId: "fixture-policy-guidance",
        revision: 1,
        basedOnRevisionId: null,
        status: "PUBLISHED",
        runtimeType: "Managed interactive",
        model: "Demo reasoning model",
        endpoint: "https://demo.invalid/agents/policy-guidance",
        mcpIds: [],
        skillIds: [],
        knowledgeBaseIds: [],
        technicalResult: {
          outcome: "PASSED",
          completedAt: createdAt,
          checks: [
            {
              id: "fixture-check",
              label: "Dependency resolution",
              status: "PASSED",
              detail: "All configured demo dependencies resolved.",
            },
          ],
        },
        businessEvaluation: {
          businessPurpose: "Provide approved policy guidance.",
          targetUsers: "Service representatives",
          criticality: "Medium",
          dataSensitivity: "Internal policy data",
          successThreshold: 85,
          datasetId: "dataset-support-readiness",
          guardrailTemplates: [],
          approvalReason: "Approved fixture for demonstration.",
          outcome: "PASSED",
          scenarioSuccess: 94,
          scenariosCovered: 8,
          residualRisk: "Low",
          estimatedCost: 0.04,
          completedAt: createdAt,
        },
        decisionReason: "Approved fixture for demonstration.",
      },
    ],
    mcpServers: [],
    skills: [],
    knowledgeBases: [],
    datasets: [
      {
        id: "dataset-support-readiness",
        demoSessionId,
        projectId,
        source: "FIXTURE",
        createdByPersona: "admin",
        createdAt,
        updatedAt: createdAt,
        name: "Customer Support Readiness",
        description: "Business scenarios for service quality and safety.",
        scenarioCount: 12,
      },
    ],
    instances: [],
    events: [],
  } satisfies DemoWorkflowState);
}
