import type { DemoWorkflowState } from "./model";

export function cloneDemoWorkflowFixtures(
  projectId: string,
  demoSessionId: string,
): DemoWorkflowState {
  const createdAt = "2026-08-01T09:00:00.000Z";
  return structuredClone({
    demoSessionId,
    projectId,
    agents: [
      {
        id: "fixture-policy-guidance",
        demoSessionId,
        projectId,
        source: "FIXTURE",
        createdByPersona: "admin",
        createdAt,
        updatedAt: createdAt,
        name: "Policy Guidance Assistant",
        owner: "Policy Operations",
        description: "Answers policy questions using approved guidance.",
        businessOutcome: "Consistent policy guidance for service teams",
        targetUsers: "Service representatives",
        typicalScenarios: ["Policy lookup", "Escalation guidance"],
        currentApprovedRevisionId: "fixture-policy-guidance-r1",
        activeDraftRevisionId: null,
      },
      {
        id: "fixture-z-service-recovery",
        demoSessionId,
        projectId,
        source: "FIXTURE",
        createdByPersona: "admin",
        createdAt,
        updatedAt: createdAt,
        name: "Service Recovery Copilot",
        owner: "Customer Experience",
        description: "Recommends consistent recovery options for escalated service cases.",
        businessOutcome: "Resolve escalations faster while preserving customer trust",
        targetUsers: "Customer service leaders",
        typicalScenarios: ["Service recovery", "Escalation guidance"],
        currentApprovedRevisionId: null,
        activeDraftRevisionId: null,
      },
      {
        id: "fixture-z-claims-review",
        demoSessionId,
        projectId,
        source: "FIXTURE",
        createdByPersona: "admin",
        createdAt,
        updatedAt: createdAt,
        name: "Claims Review Assistant",
        owner: "Claims Operations",
        description: "Prepares supervised claim reviews for specialist approval.",
        businessOutcome: "Improve claim review consistency with mandatory human oversight",
        targetUsers: "Claims specialists",
        typicalScenarios: ["Claim intake", "Policy exception review"],
        currentApprovedRevisionId: null,
        activeDraftRevisionId: null,
      },
      {
        id: "fixture-z-fraud-triage",
        demoSessionId,
        projectId,
        source: "FIXTURE",
        createdByPersona: "admin",
        createdAt,
        updatedAt: createdAt,
        name: "Fraud Triage Assistant",
        owner: "Risk Operations",
        description: "Prioritizes suspicious activity for business review.",
        businessOutcome: "Focus investigators on higher-risk activity",
        targetUsers: "Fraud operations analysts",
        typicalScenarios: ["Risk triage", "Escalation routing"],
        currentApprovedRevisionId: null,
        activeDraftRevisionId: null,
      },
    ],
    agentRevisions: [
      {
        id: "fixture-policy-guidance-r1",
        demoSessionId,
        projectId,
        source: "FIXTURE",
        createdByPersona: "admin",
        createdAt,
        updatedAt: createdAt,
        agentId: "fixture-policy-guidance",
        revision: 1,
        basedOnRevisionId: null,
        status: "PUBLISHED",
        runtimeType: "Managed interactive",
        model: "Demo reasoning model",
        endpoint: "https://demo.invalid/agents/policy-guidance",
        mcpIds: [],
        skillIds: [],
        knowledgeBaseIds: [],
        technicalResult: {
          outcome: "PASSED",
          completedAt: createdAt,
          checks: [
            {
              id: "fixture-check",
              label: "Dependency resolution",
              status: "PASSED",
              detail: "All configured demo dependencies resolved.",
            },
          ],
        },
        businessEvaluation: {
          businessPurpose: "Provide approved policy guidance.",
          targetUsers: "Service representatives",
          criticality: "Medium",
          dataSensitivity: "Internal policy data",
          successThreshold: 85,
          datasetId: "dataset-support-readiness",
          guardrailTemplates: [],
          approvalReason: "Approved fixture for demonstration.",
          outcome: "PASSED",
          scenarioSuccess: 94,
          scenariosCovered: 8,
          residualRisk: "Low",
          estimatedCost: 0.04,
          completedAt: createdAt,
        },
        decisionReason: "Approved fixture for demonstration.",
      },
      {
        id: "fixture-z-service-recovery-r1",
        demoSessionId,
        projectId,
        source: "FIXTURE",
        createdByPersona: "admin",
        createdAt,
        updatedAt: createdAt,
        agentId: "fixture-z-service-recovery",
        revision: 1,
        basedOnRevisionId: null,
        status: "PENDING_APPROVAL",
        runtimeType: "Managed interactive",
        model: "Demo reasoning model",
        endpoint: "https://demo.invalid/agents/service-recovery",
        mcpIds: [],
        skillIds: [],
        knowledgeBaseIds: [],
        technicalResult: {
          outcome: "PASSED",
          completedAt: createdAt,
          checks: [
            {
              id: "fixture-service-recovery-check",
              label: "Dependency resolution",
              status: "PASSED",
              detail: "All configured demo dependencies resolved.",
            },
          ],
        },
        businessEvaluation: {
          businessPurpose: "Resolve service escalations with consistent recovery guidance.",
          targetUsers: "Customer service leaders",
          criticality: "High",
          dataSensitivity: "Confidential customer data",
          successThreshold: 85,
          datasetId: "dataset-support-readiness",
          guardrailTemplates: [
            {
              id: "guardrail-template:universal-safety:R1",
              sourceGuardrailId: "universal-safety",
              sourceGuardrailRevisionId: "universal-safety:R1",
              version: "1",
              name: "Universal Safety Baseline",
            },
          ],
          approvalReason: "Eval evidence supports a controlled business rollout.",
          outcome: "PASSED",
          scenarioSuccess: 91,
          scenariosCovered: 8,
          residualRisk: "Low",
          estimatedCost: 0.04,
          completedAt: createdAt,
        },
        decisionReason: null,
      },
      {
        id: "fixture-z-claims-review-r1",
        demoSessionId,
        projectId,
        source: "FIXTURE",
        createdByPersona: "admin",
        createdAt,
        updatedAt: createdAt,
        agentId: "fixture-z-claims-review",
        revision: 1,
        basedOnRevisionId: null,
        status: "PENDING_APPROVAL",
        runtimeType: "Managed interactive",
        model: "Demo reasoning model",
        endpoint: "https://demo.invalid/agents/claims-review",
        mcpIds: [],
        skillIds: [],
        knowledgeBaseIds: [],
        technicalResult: {
          outcome: "PASSED",
          completedAt: createdAt,
          checks: [
            {
              id: "fixture-claims-review-check",
              label: "Dependency resolution",
              status: "PASSED",
              detail: "All configured demo dependencies resolved.",
            },
          ],
        },
        businessEvaluation: {
          businessPurpose: "Prepare supervised claim reviews for specialist approval.",
          targetUsers: "Claims specialists",
          criticality: "High",
          dataSensitivity: "Confidential customer data",
          successThreshold: 85,
          datasetId: "dataset-support-readiness",
          guardrailTemplates: [
            {
              id: "guardrail-template:universal-safety:R1",
              sourceGuardrailId: "universal-safety",
              sourceGuardrailRevisionId: "universal-safety:R1",
              version: "1",
              name: "Universal Safety Baseline",
            },
          ],
          approvalReason: "The failed Eval requires an explicit Admin risk decision.",
          outcome: "FAILED",
          scenarioSuccess: 68,
          scenariosCovered: 8,
          residualRisk: "High",
          estimatedCost: 0.04,
          completedAt: createdAt,
        },
        decisionReason: null,
      },
      {
        id: "fixture-z-fraud-triage-r1",
        demoSessionId,
        projectId,
        source: "FIXTURE",
        createdByPersona: "admin",
        createdAt,
        updatedAt: createdAt,
        agentId: "fixture-z-fraud-triage",
        revision: 1,
        basedOnRevisionId: null,
        status: "REJECTED",
        runtimeType: "Managed interactive",
        model: "Demo reasoning model",
        endpoint: "https://demo.invalid/agents/fraud-triage",
        mcpIds: [],
        skillIds: [],
        knowledgeBaseIds: [],
        technicalResult: {
          outcome: "PASSED",
          completedAt: createdAt,
          checks: [
            {
              id: "fixture-fraud-triage-check",
              label: "Dependency resolution",
              status: "PASSED",
              detail: "All configured demo dependencies resolved.",
            },
          ],
        },
        businessEvaluation: {
          businessPurpose: "Prioritize suspicious activity for investigator review.",
          targetUsers: "Fraud operations analysts",
          criticality: "High",
          dataSensitivity: "Confidential customer data",
          successThreshold: 85,
          datasetId: "dataset-support-readiness",
          guardrailTemplates: [
            {
              id: "guardrail-template:universal-safety:R1",
              sourceGuardrailId: "universal-safety",
              sourceGuardrailRevisionId: "universal-safety:R1",
              version: "1",
              name: "Universal Safety Baseline",
            },
          ],
          approvalReason: "Eval evidence met the configured quality threshold.",
          outcome: "PASSED",
          scenarioSuccess: 96,
          scenariosCovered: 8,
          residualRisk: "Low",
          estimatedCost: 0.04,
          completedAt: createdAt,
        },
        decisionReason: "The pilot owner requires stronger escalation controls before release.",
      },
    ],
    mcpServers: [
      {
        id: "demo-operations-mcp",
        demoSessionId,
        projectId,
        source: "FIXTURE",
        createdByPersona: "admin",
        createdAt,
        updatedAt: createdAt,
        name: "Operations MCP",
        endpoint: "http://localhost:3001/mcp",
        authType: "none",
      },
    ],
    skills: [
      {
        id: "demo-document-summarization",
        demoSessionId,
        projectId,
        source: "FIXTURE",
        createdByPersona: "admin",
        createdAt,
        updatedAt: createdAt,
        name: "Document Summarization",
        description: "Summarize HR documents and reports with a fixed instruction contract.",
      },
    ],
    knowledgeBases: [
      {
        id: "demo-policy-kb",
        demoSessionId,
        projectId,
        source: "FIXTURE",
        createdByPersona: "admin",
        createdAt,
        updatedAt: createdAt,
        name: "Permission Policy KB",
        sourceType: "Approved policy collection",
        description: "Approved permission policies used to ground Agent responses.",
      },
    ],
    datasets: [
      {
        id: "dataset-support-readiness",
        demoSessionId,
        projectId,
        source: "FIXTURE",
        createdByPersona: "admin",
        createdAt,
        updatedAt: createdAt,
        name: "Customer Support Readiness",
        description: "Business scenarios for service quality and safety.",
        scenarioCount: 12,
      },
    ],
    instances: [],
    events: [],
  } satisfies DemoWorkflowState);
}
